### ISSUE TITLE
Cant create swagger file

### ISSUE THREAD

**Issue by stefangrosse** [amanoooo/apidoc-swagger-3.0#1]
hello.

Thanks for this nice tool, but i run into the following issue:

at the console i start:
`apidoc-swagger-3 -f .php -i "/doc/api/" -o "//doc/api/"`

After that I get the following error message:
```
[warn] tsc error { Error: Command failed: npx tsc ./sample/index.ts
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.init (/usr/local/lib/node_modules/apidoc-swagger-3/apidoc-plugin-replace-mark.js:33:13)
    at /usr/local/lib/node_modules/apidoc-swagger-3/node_modules/apidoc-core/lib/plugin_loader.js:96:14
    at /usr/local/lib/node_modules/apidoc-swagger-3/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/usr/local/lib/node_modules/apidoc-swagger-3/node_modules/lodash/lodash.js:3032:24)
    at /usr/local/lib/node_modules/apidoc-swagger-3/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/usr/local/lib/node_modules/apidoc-swagger-3/node_modules/lodash/lodash.js:9410:14)
    at PluginLoader.loadPlugins (/usr/local/lib/node_modules/apidoc-swagger-3/node_modules/apidoc-core/lib/plugin_loader.js:88:5)
    at new PluginLoader (/usr/local/lib/node_modules/apidoc-swagger-3/node_modules/apidoc-core/lib/plugin_loader.js:27:8)
  status: 2,
  signal: null,
  output:
   [ null,
     <Buffer 73 61 6d 70 6c 65 2f 69 6e 64 65 78 2e 74 73 28 31 2c 31 29 3a 20 65 72 72 6f 72 20 54 53 32 35 38 30 3a 20 43 61 6e 6e 6f 74 20 66 69 6e 64 20 6e 61 ... >,
     <Buffer > ],
  pid: 4732,
  stdout:
   <Buffer 73 61 6d 70 6c 65 2f 69 6e 64 65 78 2e 74 73 28 31 2c 31 29 3a 20 65 72 72 6f 72 20 54 53 32 35 38 30 3a 20 43 61 6e 6e 6f 74 20 66 69 6e 64 20 6e 61 ... >,
  stderr: <Buffer > }
```

What am I doing wrong? Thanks!

**Comment by fosteradorkor** [comment]
Facing the same issue

**Comment by Chinlinlee** [comment]
I temporary solve this problem below by following the steps:

# Step 1
- Go to the `apidoc-swagger-3` global node_modules path, `C:/Users/user/AppData/Roaming/npm/node_modules/`
# Step 2
- Remove `apidoc-plugin-replace-mark.js` file

**Comment by maZahaca** [comment]
We're approaching the same issue! Any advice how to get this solved?
